site_name: Robotic Perception
nav:
    - Home: index.md
    - Introduction: Intro.md
    - Methodology: Method.md
    - Results: Results.md

theme: readthedocs
plugins:
    - search
    # - glightbox
    - mkdocs-video
    - bibtex:
        bib_file: refs.bib
        # csl_file: ieee.csl

markdown_extensions: 
  - pymdownx.arithmatex
  - admonition
  - def_list
  - attr_list
  - md_in_html
  - pymdownx.critic
#   - captions


extra_javascript:
  - javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML



