site_name: Robotic Perception
nav:
    - Home: index.md
    - Introduction: Intro.md

theme: readthedocs
plugins:
    - search
markdown_extensions: 
  - admonition
  - def_list
    #   generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js



